-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\DFII\Biquad_Filter2.vhd
-- Created: 2025-10-30 20:34:13
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Biquad_Filter2
-- Source Path: DFII/DF1/Biquad Filter2
-- Hierarchy Level: 1
-- Model version: 1.18
-- 
-- Biquad Filter
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.DF1_pkg.ALL;

ENTITY Biquad_Filter2 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dataIn                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validIn                           :   IN    std_logic;
        dataOut                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        validOut                          :   OUT   std_logic
        );
END Biquad_Filter2;


ARCHITECTURE rtl OF Biquad_Filter2 IS

  -- Component Declarations
  COMPONENT BiquadRegFile_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din                             :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          wr_addr                         :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          wr_en                           :   IN    std_logic;
          rd_addr                         :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
          rd_out                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : BiquadRegFile_block
    USE ENTITY work.BiquadRegFile_block(rtl);

  -- Constants
  CONSTANT name_table_data                : vector_of_signed16(0 TO 7) := 
    (to_signed(16#4000#, 16), to_signed(16#4000#, 16), to_signed(-16#7216#, 16), to_signed(16#4000#, 16),
     to_signed(16#7457#, 16), to_signed(-16#361D#, 16), to_signed(16#4000#, 16), to_signed(16#0000#, 16));  -- sfix16 [8]

  -- Signals
  SIGNAL preValidOut                      : std_logic;
  SIGNAL validOut_1                       : std_logic;
  SIGNAL ready                            : std_logic;
  SIGNAL readyOutDelay                    : std_logic;
  SIGNAL notReadyOut                      : std_logic;
  SIGNAL gated2Valid                      : std_logic;
  SIGNAL valid2Enable                     : std_logic;
  SIGNAL gated2ValidReg                   : std_logic;
  SIGNAL readyctrl                        : std_logic;
  SIGNAL readyDelayReg_reg                : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL readyDelay                       : std_logic;
  SIGNAL gatedValid                       : std_logic;
  SIGNAL notGatedValid                    : std_logic;
  SIGNAL preReadyOut                      : std_logic;
  SIGNAL gatedValidReg                    : std_logic;
  SIGNAL BiquadDFICtrl_state              : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL BiquadDFICtrl_circularAddr       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL BiquadDFICtrl_state_next         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL BiquadDFICtrl_circularAddr_next  : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL validoutctrl                     : std_logic;
  SIGNAL accenctrl                        : std_logic;
  SIGNAL loadaccctrl                      : std_logic;
  SIGNAL muxinctrl                        : std_logic;
  SIGNAL muxramctrl                       : std_logic;
  SIGNAL dwaddrctrl                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL dwectrl                          : std_logic;
  SIGNAL rdAddr                           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL coeffAddr                        : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL validdelayone                    : std_logic;
  SIGNAL intdelay_reg                     : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL outZero                          : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL intdelay_reg_1                   : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL accumEn                          : std_logic;
  SIGNAL dataRAMMuxCtrl                   : std_logic;
  SIGNAL intdelay_reg_2                   : std_logic_vector(3 DOWNTO 0);  -- ufix1 [4]
  SIGNAL wrDataCtrl                       : std_logic;
  SIGNAL intdelay_reg_3                   : std_logic_vector(1 DOWNTO 0);  -- ufix1 [2]
  SIGNAL gated2ValidDelay                 : std_logic;
  SIGNAL inRegMuxCtrl                     : std_logic;
  SIGNAL dataIn_signed                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataIn2Reg                       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataInReg                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL inRegMux                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL intdelay_reg_4                   : vector_of_unsigned3(0 TO 3);  -- ufix3 [4]
  SIGNAL wrAddr                           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL intdelay_reg_5                   : std_logic_vector(3 DOWNTO 0);  -- ufix1 [4]
  SIGNAL wrEn                             : std_logic;
  SIGNAL inStageReg                       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL coeffData                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL coeffOut                         : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En14
  SIGNAL coeffPreMul                      : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En14
  SIGNAL intdelay_reg_6                   : std_logic_vector(2 DOWNTO 0);  -- ufix1 [3]
  SIGNAL accumMuxCtrl                     : std_logic;
  SIGNAL accumZero                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL accum                            : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL accumMux                         : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL wrData                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL rdData                           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL rdData_signed                    : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataRAMMux                       : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataPreMul                       : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En14
  SIGNAL mulOut                           : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL postMul                          : signed(31 DOWNTO 0) := to_signed(0, 32);  -- sfix32_En28
  SIGNAL adder_add_cast                   : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL adder_add_cast_1                 : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL adder_1                          : signed(32 DOWNTO 0);  -- sfix33_En28
  SIGNAL quantizer                        : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL outMux                           : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL dataOut_tmp                      : signed(15 DOWNTO 0);  -- sfix16_En14

BEGIN
  u_BiquadRegFile : BiquadRegFile_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              din => std_logic_vector(wrData),  -- sfix16_En14
              wr_addr => std_logic_vector(wrAddr),  -- ufix3
              wr_en => wrEn,
              rd_addr => std_logic_vector(rdAddr),  -- ufix3
              rd_out => rdData  -- sfix16_En14
              );

  ValidOutRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validOut_1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validOut_1 <= preValidOut;
      END IF;
    END IF;
  END PROCESS ValidOutRegister_process;


  readyOutDelayReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      readyOutDelay <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        readyOutDelay <= ready;
      END IF;
    END IF;
  END PROCESS readyOutDelayReg_process;


  notReadyOut <=  NOT ready;

  gated2Valid <= validIn AND (notReadyOut AND readyOutDelay);

  valid2Enable <= gated2Valid OR validOut_1;

  valid2Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gated2ValidReg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND valid2Enable = '1' THEN
        gated2ValidReg <= gated2Valid;
      END IF;
    END IF;
  END PROCESS valid2Register_process;


  readyDelayReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      readyDelayReg_reg <= (OTHERS => '1');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        readyDelayReg_reg(0) <= readyctrl;
        readyDelayReg_reg(2 DOWNTO 1) <= readyDelayReg_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS readyDelayReg_process;

  readyDelay <= readyDelayReg_reg(2);

  notGatedValid <=  NOT gatedValid;

  preReadyOut <= readyDelay AND (notGatedValid AND readyctrl);

  ReadyOutRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ready <= '1';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        ready <= preReadyOut;
      END IF;
    END IF;
  END PROCESS ReadyOutRegister_process;


  gatedValid <= ready AND validIn;

  gateValidReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      gatedValidReg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        gatedValidReg <= gatedValid;
      END IF;
    END IF;
  END PROCESS gateValidReg_process;


  -- Controller for Biquad DFI Fully Serial
  BiquadDFICtrl_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      BiquadDFICtrl_state <= to_unsigned(16#00#, 8);
      BiquadDFICtrl_circularAddr <= to_unsigned(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        BiquadDFICtrl_state <= BiquadDFICtrl_state_next;
        BiquadDFICtrl_circularAddr <= BiquadDFICtrl_circularAddr_next;
      END IF;
    END IF;
  END PROCESS BiquadDFICtrl_process;

  BiquadDFICtrl_output : PROCESS (BiquadDFICtrl_circularAddr, BiquadDFICtrl_state, gated2ValidReg,
       gatedValidReg)
    VARIABLE add_temp : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_0 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_1 : unsigned(1 DOWNTO 0);
    VARIABLE add_temp_2 : unsigned(1 DOWNTO 0);
  BEGIN
    add_temp := to_unsigned(16#0#, 2);
    add_temp_0 := to_unsigned(16#0#, 2);
    add_temp_1 := to_unsigned(16#0#, 2);
    add_temp_2 := to_unsigned(16#0#, 2);
    BiquadDFICtrl_circularAddr_next <= BiquadDFICtrl_circularAddr;
    validoutctrl <= '0';
    readyctrl <= '1';
    accenctrl <= '0';
    loadaccctrl <= '0';
    muxinctrl <= '0';
    dwectrl <= '0';
    dwaddrctrl <= to_unsigned(16#0#, 3);
    rdAddr <= to_unsigned(16#0#, 3);
    coeffAddr <= to_unsigned(16#0#, 3);
    BiquadDFICtrl_state_next <= to_unsigned(16#00#, 8);
    CASE BiquadDFICtrl_state IS
      WHEN "00000000" =>
        IF (gatedValidReg OR gated2ValidReg) = '1' THEN 
          BiquadDFICtrl_state_next <= to_unsigned(16#01#, 8);
          muxinctrl <= '1';
          dwaddrctrl <= '0' & BiquadDFICtrl_circularAddr;
          loadaccctrl <= '1';
          accenctrl <= '1';
          dwectrl <= '1';
          readyctrl <= '0';
        END IF;
      WHEN "00000001" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#02#, 8);
        coeffAddr <= to_unsigned(16#2#, 3);
        add_temp := BiquadDFICtrl_circularAddr + to_unsigned(16#1#, 2);
        rdAddr <= '0' & add_temp;
        dwaddrctrl <= '0' & BiquadDFICtrl_circularAddr;
        loadaccctrl <= '1';
        accenctrl <= '1';
        readyctrl <= '0';
      WHEN "00000010" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#03#, 8);
        coeffAddr <= to_unsigned(16#3#, 3);
        add_temp_0 := BiquadDFICtrl_circularAddr + to_unsigned(16#2#, 2);
        rdAddr <= '0' & add_temp_0;
        dwaddrctrl <= '0' & BiquadDFICtrl_circularAddr;
        accenctrl <= '1';
        readyctrl <= '0';
      WHEN "00000011" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#04#, 8);
        coeffAddr <= to_unsigned(16#4#, 3);
        add_temp_1 := BiquadDFICtrl_circularAddr + to_unsigned(16#1#, 2);
        rdAddr <= '1' & add_temp_1;
        dwaddrctrl <= '0' & BiquadDFICtrl_circularAddr;
        accenctrl <= '1';
        readyctrl <= '0';
      WHEN "00000100" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#05#, 8);
        coeffAddr <= to_unsigned(16#5#, 3);
        add_temp_2 := BiquadDFICtrl_circularAddr + to_unsigned(16#2#, 2);
        rdAddr <= '1' & add_temp_2;
        dwaddrctrl <= '0' & BiquadDFICtrl_circularAddr;
        accenctrl <= '1';
        readyctrl <= '0';
      WHEN "00000101" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#06#, 8);
        coeffAddr <= to_unsigned(16#1#, 3);
        rdAddr <= '0' & BiquadDFICtrl_circularAddr;
        dwaddrctrl <= '1' & BiquadDFICtrl_circularAddr;
        accenctrl <= '1';
        dwectrl <= '1';
        readyctrl <= '0';
      WHEN "00000110" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#07#, 8);
        readyctrl <= '0';
      WHEN "00000111" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#08#, 8);
        readyctrl <= '0';
      WHEN "00001000" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#09#, 8);
        readyctrl <= '0';
      WHEN "00001001" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#0A#, 8);
        readyctrl <= '0';
      WHEN "00001010" =>
        IF gated2ValidReg = '1' THEN 
          BiquadDFICtrl_state_next <= to_unsigned(16#0B#, 8);
        END IF;
        coeffAddr <= to_unsigned(16#6#, 3);
        rdAddr <= '1' & BiquadDFICtrl_circularAddr;
        dwaddrctrl <= '1' & BiquadDFICtrl_circularAddr;
        loadaccctrl <= '1';
        accenctrl <= '1';
        validoutctrl <= '1';
        BiquadDFICtrl_circularAddr_next <= BiquadDFICtrl_circularAddr + to_unsigned(16#3#, 2);
        readyctrl <= '0';
      WHEN "00001011" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#0C#, 8);
        readyctrl <= '0';
      WHEN "00001100" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#0D#, 8);
        readyctrl <= '0';
      WHEN "00001101" =>
        BiquadDFICtrl_state_next <= to_unsigned(16#0E#, 8);
        readyctrl <= '0';
      WHEN "00001110" =>
        readyctrl <= '0';
      WHEN OTHERS => 
        NULL;
    END CASE;
    muxramctrl <= '0';
  END PROCESS BiquadDFICtrl_output;


  validdelayonereg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      validdelayone <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        validdelayone <= validoutctrl;
      END IF;
    END IF;
  END PROCESS validdelayonereg_process;


  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg(0) <= validdelayone;
        intdelay_reg(2 DOWNTO 1) <= intdelay_reg(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_process;

  preValidOut <= intdelay_reg(2);

  outZero <= to_signed(16#0000#, 16);

  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg_1 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg_1(0) <= accenctrl;
        intdelay_reg_1(2 DOWNTO 1) <= intdelay_reg_1(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_1_process;

  accumEn <= intdelay_reg_1(2);

  intdelay_2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataRAMMuxCtrl <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dataRAMMuxCtrl <= muxinctrl;
      END IF;
    END IF;
  END PROCESS intdelay_2_process;


  intdelay_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg_2 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg_2(0) <= muxramctrl;
        intdelay_reg_2(3 DOWNTO 1) <= intdelay_reg_2(2 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_3_process;

  wrDataCtrl <= intdelay_reg_2(3);

  intdelay_4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg_3 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg_3(0) <= gated2ValidReg;
        intdelay_reg_3(1) <= intdelay_reg_3(0);
      END IF;
    END IF;
  END PROCESS intdelay_4_process;

  gated2ValidDelay <= intdelay_reg_3(1);

  inRegMuxCtrl <=  NOT gated2ValidDelay;

  dataIn_signed <= signed(dataIn);

  InputReg2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataIn2Reg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND gated2Valid = '1' THEN
        dataIn2Reg <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS InputReg2_process;


  InputReg1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataInReg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dataInReg <= dataIn_signed;
      END IF;
    END IF;
  END PROCESS InputReg1_process;


  
  inRegMux <= dataIn2Reg WHEN inRegMuxCtrl = '0' ELSE
      dataInReg;

  intdelay_5_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg_4 <= (OTHERS => to_unsigned(16#0#, 3));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg_4(0) <= dwaddrctrl;
        intdelay_reg_4(1 TO 3) <= intdelay_reg_4(0 TO 2);
      END IF;
    END IF;
  END PROCESS intdelay_5_process;

  wrAddr <= intdelay_reg_4(3);

  intdelay_6_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg_5 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg_5(0) <= dwectrl;
        intdelay_reg_5(3 DOWNTO 1) <= intdelay_reg_5(2 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_6_process;

  wrEn <= intdelay_reg_5(3);

  inStageRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      inStageReg <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        inStageReg <= inRegMux;
      END IF;
    END IF;
  END PROCESS inStageRegister_process;


  coeffData <= name_table_data(to_integer(coeffAddr));

  coeffOutReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffOut <= coeffData;
      END IF;
    END IF;
  END PROCESS coeffOutReg_process;


  coeffPipeReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        coeffPreMul <= coeffOut;
      END IF;
    END IF;
  END PROCESS coeffPipeReg_process;


  intdelay_7_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      intdelay_reg_6 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        intdelay_reg_6(0) <= loadaccctrl;
        intdelay_reg_6(2 DOWNTO 1) <= intdelay_reg_6(1 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS intdelay_7_process;

  accumMuxCtrl <= intdelay_reg_6(2);

  accumZero <= to_signed(16#0000#, 16);

  
  accumMux <= accum WHEN accumMuxCtrl = '0' ELSE
      accumZero;

  
  wrData <= accum WHEN wrDataCtrl = '0' ELSE
      inRegMux;

  rdData_signed <= signed(rdData);

  
  dataRAMMux <= rdData_signed WHEN dataRAMMuxCtrl = '0' ELSE
      inStageReg;

  dataPipeReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dataPreMul <= dataRAMMux;
      END IF;
    END IF;
  END PROCESS dataPipeReg_process;


  mulOut <= dataPreMul * coeffPreMul;

  posMulPipeReg_process : PROCESS (clk)
  BEGIN
    IF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        postMul <= mulOut;
      END IF;
    END IF;
  END PROCESS posMulPipeReg_process;


  adder_add_cast <= resize(postMul, 33);
  adder_add_cast_1 <= resize(accumMux & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33);
  adder_1 <= adder_add_cast + adder_add_cast_1;

  
  quantizer <= X"7FFF" WHEN ((adder_1(32) = '0') AND (adder_1(31 DOWNTO 29) /= "000")) OR ((adder_1(32) = '0') AND (adder_1(29 DOWNTO 14) = X"7FFF")) ELSE
      X"8000" WHEN (adder_1(32) = '1') AND (adder_1(31 DOWNTO 29) /= "111") ELSE
      adder_1(29 DOWNTO 14) + ('0' & (adder_1(13) AND (( NOT adder_1(32)) OR (adder_1(12) OR adder_1(11) OR adder_1(10) OR adder_1(9) OR adder_1(8) OR adder_1(7) OR adder_1(6) OR adder_1(5) OR adder_1(4) OR adder_1(3) OR adder_1(2) OR adder_1(1) OR adder_1(0)))));

  accumReg_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      accum <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND accumEn = '1' THEN
        accum <= quantizer;
      END IF;
    END IF;
  END PROCESS accumReg_process;


  
  outMux <= outZero WHEN preValidOut = '0' ELSE
      accum;

  OutRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dataOut_tmp <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dataOut_tmp <= outMux;
      END IF;
    END IF;
  END PROCESS OutRegister_process;


  dataOut <= std_logic_vector(dataOut_tmp);

  validOut <= validOut_1;

END rtl;

