-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\DFII\Filter_Processing1.vhd
-- Created: 2025-10-26 23:49:30
-- 
-- Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 2.08333e-05
-- Target subsystem base rate: 2.08333e-05
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        2.08333e-05
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Filter_Processing1
-- Source Path: DFII/Filter Processing1
-- Hierarchy Level: 0
-- Model version: 1.16
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Filter_Processing1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2_E1
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END Filter_Processing1;


ARCHITECTURE rtl OF Filter_Processing1 IS

  -- Component Declarations
  COMPONENT Biquad_Filter
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(1 DOWNTO 0);  -- sfix2_E1
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Biquad_Filter2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Biquad_Filter3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          validIn                         :   IN    std_logic;
          dataOut                         :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Biquad_Filter
    USE ENTITY work.Biquad_Filter(rtl);

  FOR ALL : Biquad_Filter2
    USE ENTITY work.Biquad_Filter2(rtl);

  FOR ALL : Biquad_Filter3
    USE ENTITY work.Biquad_Filter3(rtl);

  -- Signals
  SIGNAL Constant_out1                    : std_logic;
  SIGNAL Biquad_Filter_out1               : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Biquad_Filter_out2               : std_logic;
  SIGNAL Biquad_Filter2_out1              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Biquad_Filter2_out2              : std_logic;
  SIGNAL Biquad_Filter3_out1              : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Biquad_Filter : Biquad_Filter
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => In1,  -- sfix2_E1
              validIn => Constant_out1,
              dataOut => Biquad_Filter_out1,  -- sfix16_En14
              validOut => Biquad_Filter_out2
              );

  u_Biquad_Filter2 : Biquad_Filter2
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => Biquad_Filter_out1,  -- sfix16_En14
              validIn => Biquad_Filter_out2,
              dataOut => Biquad_Filter2_out1,  -- sfix16_En14
              validOut => Biquad_Filter2_out2
              );

  u_Biquad_Filter3 : Biquad_Filter3
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              dataIn => Biquad_Filter2_out1,  -- sfix16_En14
              validIn => Biquad_Filter2_out2,
              dataOut => Biquad_Filter3_out1  -- sfix16_En14
              );

  Constant_out1 <= '1';

  ce_out <= clk_enable;

  Out1 <= Biquad_Filter3_out1;

END rtl;

